import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Provider from '@/components/Hoc/Provider';
import ResponsiveNav from '@/components/Navbar/ResponsiveNav';
import Footer from '@/components/Home/Footer/Footer';
import ScrollToTop from '@/components/Helper/ScrollToTop';

const font = Inter({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'my-portfolio-website || WebDev',
  description: 'Generated by Kyaching DevPortfolio website',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} antialiased`}>
        <Provider>
          <ResponsiveNav />
          {children}
          <Footer />
          <ScrollToTop/>
        </Provider>
      </body>
    </html>
  );
}
